### ISSUE TITLE
Update offline docs to 3.3.2

### ISSUE THREAD

**Issue by brutalcrozt** [AAlakkad/Bootstrap-3-Offline-Docs#2]
hey dude thanks anyway, i use this documentation, then for several reason have to get the documentation v 3.3.2 . With some search for 2 days now i get compiled offline documentation. But can you tell me how to make this accessible without jekyll?

if you let me i want update your repo

**Comment by AAlakkad** [comment]
If you've compiled them using Jekyll, you just need the files inside the output folder.
