### ISSUE TITLE
chm version ?

### ISSUE THREAD

**Issue by aviaryan** [AAlakkad/Bootstrap-3-Offline-Docs#4]
Do you have  plans for offering a CHM version of the documentation.
That would be super-convenient. 

Thanks

**Comment by AAlakkad** [comment]
Thank you for the suggestion.

Actually I don't use CHM nor know how to create one. if anyone can provide
such thing I'd merge it.


Best Regards,



 Ammar Alakkad
 Web Developer,
 m: +963-958280972
 s: http://aalakkad.me
  <http://twitter.com/Am_Alakkad>  <https://www.linkedin.com/in/AAlakkad>

**Comment by aviaryan** [comment]
No problem.
Actually I have had some experience with CHM and I can code a bit, so maybe I will give this a try. 
No promises, though.

**Comment by aviaryan** [comment]
I did it, but it was way more tedious and complicated than I thought.. 
For creating the chm source files, I had to remove all javascript from the pages as well as add new files. I have made it into a project, you can find it at https://github.com/aviaryan/bootstrap-chm
