### ISSUE TITLE
Idea: Link directly to index.html

### ISSUE THREAD

**Issue by luisperezphd** [AAlakkad/Bootstrap-3-Offline-Docs#6]
First thanks for making this available. This isn't an issue just an idea/suggestion. What do you think about changing the links so that they link directly to the index.html so that the documents work offline without a web server.

Right now if I download the documentation then click on "CSS" it takes me to the "/css" folder. At which point at least in Chrome I get a list of the files at that location instead of the actual CSS documentation. If it linked to "/css/index.html".

Very minor, thought I'd mention it. Again thanks for making this available, appreciate it.

**Comment by AAlakkad** [comment]
Probably it' an issue from the browser, any way I've changed that to point directly to the `index.html` for home page only.
